const data = {
  Info: "This is Official data of a customer with dealer",
  dealer: {
    id: "dealer_1",
    name: "dealer_abc",
    address: "PQRS DEF LMN",
    phoneNo: "9955778844",
  },
  customer: {
    id: "customer_1",
    name: "customer_abc",
    address: "XYZ ABC MNOP",
    phoneNo: "8498542489",
  },

  cars: [
    {
      name: "chevrolet chevelle malibu",
      miles_per_gallon: 18,
      cylinders: 8,
      displacement: 307,
      horsepower: 130,
      weight_in_lbs: 3504,
      accelaration: 12,
      year: "1970-01-01",
      origin: "USA",
    },
    {
      name: "buick skylark 320",
      miles_per_gallon: 15,
      cylinders: 8,
      displacement: 350,
      horsepower: 165,
      weight_in_lbs: 3693,
      Acceleration: 11.5,
      year: "1970-01-01",
      origin: "USA",
    },
    {
      name: "plymouth satellite",
      miles_per_gallon: 18,
      cylinders: 8,
      displacement: 318,
      horsepower: 150,
      weight_in_lbs: 3436,
      Acceleration: 11,
      year: "1970-01-01",
      origin: "USA",
    },
    {
      name: "amc rebel sst",
      miles_per_gallon: 16,
      cylinders: 8,
      displacement: 304,
      horsepower: 150,
      weight_in_lbs: 3433,
      Acceleration: 12,
      year: "1970-01-01",
      origin: "USA",
    },
    {
      name: "ford torino",
      miles_per_gallon: 17,
      cylinders: 8,
      displacement: 302,
      horsepower: 140,
      weight_in_lbs: 3449,
      Acceleration: 10.5,
      year: "1970-01-01",
      origin: "USA",
    },
    {
      name: "ford galaxie 500",
      miles_per_gallon: 15,
      cylinders: 8,
      displacement: 429,
      horsepower: 198,
      weight_in_lbs: 4341,
      Acceleration: 10,
      year: "1970-01-01",
      origin: "USA",
    },
    {
      name: "chevrolet impala",
      miles_per_gallon: 14,
      cylinders: 8,
      displacement: 454,
      horsepower: 220,
      weight_in_lbs: 4354,
      Acceleration: 9,
      year: "1970-01-01",
      origin: "USA",
    },
    {
      name: "plymouth fury iii",
      miles_per_gallon: 14,
      cylinders: 8,
      displacement: 440,
      horsepower: 215,
      weight_in_lbs: 4312,
      Acceleration: 8.5,
      year: "1970-01-01",
      origin: "USA",
    },
    {
      name: "pontiac catalina",
      miles_per_gallon: 14,
      cylinders: 8,
      displacement: 455,
      horsepower: 225,
      weight_in_lbs: 4425,
      Acceleration: 10,
      year: "1970-01-01",
      origin: "USA",
    },
    {
      name: "amc ambassador dpl",
      miles_per_gallon: 15,
      cylinders: 8,
      displacement: 390,
      horsepower: 190,
      weight_in_lbs: 3850,
      Acceleration: 8.5,
      year: "1970-01-01",
      origin: "USA",
    },
  ],
};
export default data;